### PR TITLE
fix(agent): Improve message conversion to JSON

### PR DESCRIPTION
**Pull request by mfulb**
This PR improves the conversion of log message strings to JSON for transmission to the collector.

### CODE REVIEW

**Comment by mfulb** [comment]
ok jenkins

**Comment by mfulb** [comment]
ok jenkins

**Review by ZNeumann — APPROVED** [review]
Nice tests

**Comment by mfulb** [comment]
ok jenkins

**Review by zsistla — APPROVED** [review]

**Review by misiekn — APPROVED** [review]

**Pull request merged**
