### PR TITLE
fix(docker): Added amd64 tag so mysqld will run on arm64

### PR DESCRIPTION
**Pull request by bduranleau-nr**

### CODE REVIEW

**Comment by bduranleau-nr** [comment]
ok jenkins

**Review by ZNeumann — APPROVED** [review]

**Review by misiekn — APPROVED** [review]
👍

**Review by mfulb — APPROVED** [review]
Thanks Brian!

**Comment by mfulb** [comment]
ok jenkins

**Review by zsistla — APPROVED** [review]
Nice addition, thanks!

**Comment by bduranleau-nr** [comment]
ok jenkins

**Pull request merged**
