### PR TITLE
Release 10.11 Amendment

### PR DESCRIPTION
**Pull request by ZNeumann**

### CODE REVIEW

**Review by lavarou — APPROVED** [review]
👍

**Comment by zsistla** [comment]
Do we need to call it a patch?  Technically 10.11 didn't go out yet.

**Comment by lavarou** [comment]
> Do we need to call it a patch? Technically 10.11 didn't go out yet.

Maybe the word 'patch' could be improved upon. However PR titles are by default used as merge commit messages and therefore it makes sense to differentiate this pull request from #677, which is already called 'Release 10.11'. This PR is an amendment to #677 so maybe 'amendment' instead of 'patch'? @ZNeumann @zsistla

**Comment by ZNeumann** [comment]
ok jenkins

**Review by zsistla — APPROVED** [review]

**Pull request merged**
