### PR TITLE
chore(install): Disable ZTS installs

### PR DESCRIPTION
**Pull request by mfulb**
Removes support for ZTS installs in `newrelic-install.sh` as disables building ZTS artifacts.

### CODE REVIEW

**Comment by ZNeumann** [comment]
How extensive should the ZTS scrubbing be in this PR? There are ZTS ifdefs/mentions in the agent and release.mk too

**Comment by mfulb** [comment]
> 

Good point I could pull those into this.

**Comment by zsistla** [comment]
> > 
> 
> I'll fix the release.mk but the ZTS ifdefs are for another day.

Agreed.
There are extensive ztz ifdefs in the agent code.
Possibly removing them and PHP 5.x (when it is eoled) can be an entire MMF effort in and of itself.

**Review by ZNeumann — APPROVED** [review]

**Review by lavarou — APPROVED** [review]
LGTM. Nice job 🧹 ZTS 🗑️ !

**Review by zsistla — APPROVED** [review]

**Comment by zsistla** [comment]
ok jenkins

**Comment by mfulb** [comment]
ok jenkins

**Review by lavarou — APPROVED** [review]

**Comment by zsistla** [comment]
@mfulb
Can you please reopen this PR against `dev`?

**Comment by lavarou** [comment]
> @mfulb Can you please reopen this PR against `dev`?

@mfulb @zsistla It is probably best to revert this change from `oapi` branch before applying it to `dev` (and `main`). This will avoid `dev`->`oapi` merge conflicts.

**Comment by lavarou** [comment]
@mfulb @zsistla Also, with new release pipeline, only https://github.com/newrelic/newrelic-php-agent/pull/636/commits/d17310de4ba25f580814a6ed6a8bb273a3ab44b8 is needed.

**Comment by zsistla** [comment]
@lavarou aren't the release.mk updates from [7675993](https://github.com/newrelic/newrelic-php-agent/pull/636/commits/76759931af7d974868bd0aa6014c7e99ef2aa07c) also needed:
https://github.com/newrelic/newrelic-php-agent/pull/636/commits/76759931af7d974868bd0aa6014c7e99ef2aa07c#diff-70acc2689fb0b36f116699b4dd558c7361f4cc683cd8a4dd6f1e559a76e9a674L99

**Comment by lavarou** [comment]
> @lavarou aren't the release.mk updates from [7675993](https://github.com/newrelic/newrelic-php-agent/pull/636/commits/76759931af7d974868bd0aa6014c7e99ef2aa07c) also needed?

@zsistla New pipeline is using [this target](https://github.com/newrelic/newrelic-php-agent/blob/main/make/release.mk#L123-L132), added in #620.

**Pull request merged**
