### PR TITLE
feat(daemon): add supportability metrics for new response codes and for harvest endpoints

### PR DESCRIPTION
**Pull request by zsistla**
Very rough prototype for addressing issue $445

1) Adds httperror metrics for new response codes
2) Adds metrics for these endpoints: https://github.com/newrelic/newrelic-php-agent/blob/main/src/newrelic/harvest.go#L139

Needs:
1) Validation
2) Test cases
3) has not added duration, but harvest has a start time, so could theoretically be added

### CODE REVIEW

**Comment by ZNeumann** [comment]
Added the a test for the new supportability metrics and ran gofmt on the test file. Hiding whitespace changes is recommended to review this PR

**Comment by zsistla** [comment]
* Validated correctness
* Added NumFailedAttempts function to Events and Metrics
* collect metrics for the events/metrics we support retries with  
The value is the number of times the agent attempted to call the given endpoint before it was successful. This metric MUST NOT be generated if only one attempt was made.

For PHP, only metricEvents, ErrorEvents, CustomEvents, TxnEvents, and SpanEvents are retried; therefore only those will ever have a count higher than 0 failed attemps.  For more details, see:
The Data Collection Limits section of Collector-Response-Handling.md in the agent-specs.

* Added additional test for cases that should or should not send the new Attempts metric.
* removed IncrementEndpointsAttempted as it was counting incorrectly 

The duration metric is NOT supported at this time.

**Comment by zsistla** [comment]
ok jenkins

**Comment by zsistla** [comment]
ok jenkins

**Comment by zsistla** [comment]
ok jenkins

**Review by ZNeumann — APPROVED** [review]

**Review by mfulb — APPROVED** [review]
Nice efficient solution.

**Pull request merged**
