### PR TITLE
Relay support

### LINKED ISSUE #522: Add support for the PhpRedis compatible extension Relay
We'd like to add support in NewRelic for the [Relay](https://relay.so/) Redis client extension.

## Summary

Relay is a drop-in replacement for the PhpRedis extension that supports caching keys in-memory with the help of Redis' server-assisted client-side caching functionality.
 
## Desired Behavior

NewRelic would track timings when using the `Relay` extension just like it does when users use `PhpRedis`.

## Possible Solution

I've written the code, I'd just like a bit of clarification as to the preferred logic changes before opening a PR.

---

Hi everyone :wave:

I've implemented support for the [Relay](https://relay.so/) extension in my fork of NewRelic but was unsure how NewRelic would prefer the mechanics to work, so I'm asking here.

Relay is a drop-in replacement for PhpRedis, meaning it's possible to simply forward any `\Relay\Relay` calls through the existing PhpHandlers.

[I did that in this branch on my fork](https://github.com/michael-grunder/newrelic-php-agent/tree/relay-support)

Since separate logic may be preferable, it's also possible to create the same handlers but for Relay.  I don't like the code duplication this causes but can see the utility of distinct logic in the event that the two extensions diverge over time:

[Here's the branch with the logic separated](https://github.com/michael-grunder/newrelic-php-agent/tree/relay-support-separate)

If I could get some direction as to which strategy the NewRelic team prefers, I'll be happy to formalize the logic and open a PR

Cheers!

### PR DESCRIPTION
**Pull request by michael-grunder**
Hi everyone :wave:

I took a guess that the preference would be separate logic.  Just let me know if you would like me to restructure the PR in any way and I'm happy to make any changes.

Closes #522

### CODE REVIEW

**Comment by tillkruss** [comment]
This is a follow-up of #481.

**Comment by tillkruss** [comment]
@misiekn: Any chance for a review?

**Comment by ak-war** [comment]
Hi @tillkruss, we highly appreciate your contributions and feedback for the New Relic PHP agent. However, currently our priority is for supporting Open Source standards, instrumentation and collaboration. Unfortunately at this time we are unable to support reviewing the current PR.

**Comment by ak-war** [comment]
Closing this issue following my comment above.

**Comment by tfanelli** [comment]
@ak-war please reconsider your position. We are asking for our customers as hosting providers, we have thousands of collective customers using New Relic. Relay is now supported officially by some of the largest hosting providers in the industry for higher end performance based sites, which translate to high value New Relic customers. Currently Pagely, Platform.sh, Convesio, and Cloudways, recently acquired by Digital Ocean (I am sure you can infer where that relationship is going). I know its Early and Relay is prob not on your radar, but @tillkruss has over 100k sites running his Redis plugin and Relay is the future of Redis+WordPress. Hopefully this gives you enough details to reconsider.

**Comment by bgabler** [comment]
@ak-war I agree with @tfanelli, we really need Relay support if we're going to continue to innovate and support things like New Relic. Considering the work is already done, doesn't seem like a crazy ask? 

Also, not sure I understand that opensource statement when you support things like Redis Enterprise, Amazon products, Rayfay.... etc.

**Pull request closed without merging**
