### PR TITLE
Roll version forward to 9.15

### PR DESCRIPTION
**Pull request by Fahmy-Mohammed**
Rolling the agent version forward to `9.15`. We are at `V` for our color that is also a food. `Vanilla` is an obvious choice here but feel free to make any other [suggestions](https://en.wikipedia.org/wiki/List_of_colors_(compact)#U%E2%80%93V)

Also started a "changelog" [draft](https://github.com/newrelic/newrelic-php-agent/releases/tag/untagged-724be0568d3160105939) for the next release that we can fill in as we go along

### CODE REVIEW

**Review by joshuabenuck — DISMISSED** [review]

**Comment by Fahmy-Mohammed** [comment]
ok jenkins

**Review by zsistla — DISMISSED** [review]

**Comment by Fahmy-Mohammed** [comment]
ok jenkins

**Review by pyohannes — DISMISSED** [review]

**Comment by pyohannes** [comment]
ok jenkins

**Comment by pyohannes** [comment]
ok jenkins

**Comment by pyohannes** [comment]
ok jenkins

**Review by joshuabenuck — APPROVED** [review]

**Pull request merged**
