### PR TITLE
Update vendor/protobuf to v3.13.0 for PHP 8 compilation compatibility

### PR DESCRIPTION
**Pull request by kneitinger**
In preparation for PHP 8, or more specifically, compilation of the agent on systems that only have PHP 8 libs/binaries, vendored `protobuf` dependency was updated to a version that accounts for those API changes.

This largely does not affect the agent, as we do not use the PHP protobuf extension, but for maintainability purposes, we do not heavily modify the `protobuf` directory's build system (which compiles language specific comilers ~by default~ in all cases)

Per `vendor/README.md` we remove the `benchmark/go` and `examples` directories.

Compilation tested on Ubuntu 20.04 + PHP 7.4 & 8.0, and Ubuntu 16.04 + PHP 5.6-7.3

### CODE REVIEW

**Comment by kneitinger** [comment]
PR pending upcoming continuation of PHP 8 support work.

**Comment by kneitinger** [comment]
ok jenkins

**Comment by kneitinger** [comment]
Fixes #43

**Comment by kneitinger** [comment]
ok jenkins

**Review by joshuabenuck — APPROVED** [review]

**Pull request merged**
