### PR TITLE
PHP:  Release Build workflow

### PR DESCRIPTION
**Pull request by zsistla**
Release build workflow which must be manually triggered as it does not trigger on push/pull.

### CODE REVIEW

**Review by joshuabenuck — APPROVED** [review]

**Comment by zsistla** [comment]
ok jenkins

**Comment by zsistla** [comment]
ok jenkins

**Comment by zsistla** [comment]
ok jenkins

**Comment by zsistla** [comment]
ok jenkins

**Review by Fahmy-Mohammed — APPROVED** [review]

**Pull request merged**
