### PR TITLE
[WIP] feat(agent/daemon): Update flatbuffers for flatc v2.0.6 [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by mfulb**
This change is mostly just updating the autogenerated files from
flatc to accomodate v2.0.6 of this compiler.

I also added a entry in the App table for the log event max limit.

### CODE REVIEW

**Review by zsistla — APPROVED** [review]
Looks good, thanks for updating.

**Comment by zsistla** [comment]
What if we separate the PRs for the 2.06 upgrades from the max logs update?

**Comment by mfulb** [comment]
I plan on doing that - I just put up what I was working on for a quick review.
I'll make a PR to move the unchanged protocol.fbs to the output from flatc v2.0.6.
Then another for the feature work I'm doing for logging.

**Comment by zsistla** [comment]
Ah, got it :)

**Comment by mfulb** [comment]
Never intended to merge so closing.

**Pull request closed without merging**
