### PR TITLE
chore(agent): Set version to 10.3.0

### PR DESCRIPTION
**Pull request by mfulb**

### CODE REVIEW

**Review by ZNeumann — APPROVED** [review]

**Review by bduranleau-nr — APPROVED** [review]

**Review by misiekn — APPROVED** [review]

**Comment by mfulb** [comment]
ok jenkins

**Comment by mfulb** [comment]
ok jenkins

**Comment by mfulb** [comment]
ok jenkins

**Comment by mfulb** [comment]
ok jenkins

**Pull request merged**
