### PR TITLE
feat(agent): use Observer API to hook into Zend Engine for PHPs 8.0+

### PR DESCRIPTION
**Pull request by zsistla**
Use Zend's Observer API to hook into Zend Engine and instrument user functions for PHPs 8.0+. This method of hooking into Zend Engine is compatible with Zend Engine's JIT, which will no longer be disabled when the agent is installed.

### CODE REVIEW

**Comment by zsistla** [comment]
ok jenkins

**Comment by zsistla** [comment]
ok jenkins

**Comment by zsistla** [comment]
ok jenkins

**Comment by zsistla** [comment]
ok jenkins

**Comment by zsistla** [comment]
ok jenkins

**Comment by zsistla** [comment]
ok jenkins

**Comment by zsistla** [comment]
ok jenkins

**Review by ZNeumann — APPROVED** [review]

**Review by lavarou — APPROVED** [review]

**Pull request merged**
