### PR TITLE
chore: Remove ZTS from builds and installs [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by mfulb**

### CODE REVIEW

**Comment by mfulb** [comment]
ok jenkins

**Review by ZNeumann — APPROVED** [review]
Much simplified!

**Review by zsistla — APPROVED** [review]
Looks good, thanks.  Is there a reason it says `do not merge`?
This can be merged with oapi branch, right?

**Comment by mfulb** [comment]
This PR has been replaced by #636 so closing now.

**Pull request closed without merging**
