### PR TITLE
tests(clm): update existing test framework with CLM support OBD

### PR DESCRIPTION
**Pull request by bduranleau-nr**
This PR is responsible for updating the existing test framework to function with CLM enabled by default.
Where necessary, the tests have been separated by PHP version, since PHP < 7.0 does not work with CLM at all.

### CODE REVIEW

**Comment by bduranleau-nr** [comment]
ok jenkins

**Comment by bduranleau-nr** [comment]
ok jenkins

**Comment by bduranleau-nr** [comment]
ok jenkins

**Comment by bduranleau-nr** [comment]
ok jenkins

**Comment by zsistla** [comment]
ok jenkins

**Comment by zsistla** [comment]
ok jenkins

**Comment by zsistla** [comment]
ok jenkins

**Comment by zsistla** [comment]
ok jenkins

**Comment by bduranleau-nr** [comment]
ok jenkins

**Comment by bduranleau-nr** [comment]
ok jenkins

**Comment by bduranleau-nr** [comment]
ok jenkins

**Review by ZNeumann — APPROVED** [review]

**Review by mfulb — APPROVED** [review]

**Review by zsistla — APPROVED** [review]

**Pull request merged**
