### PR TITLE
Fixes `mysqli_commit` instrumentation returning NULL in some cases.

### PR DESCRIPTION
**Pull request by zsistla**
* Fixes `mysqli_commit` instrumentation returning NULL.
* Utilizes already existing function to more cleanly handle the datastore segment.

### CODE REVIEW

**Comment by zsistla** [comment]
Fixes #144 .

**Comment by joshuabenuck** [comment]
What caused the `null`? If I'm reading this properly, you switched from some custom code to instrument `mysqli_commit` to calling `nr_php_instrument_datastore_operation_call`.

**Comment by zsistla** [comment]
I built 9.16 with just the mysqli commit, then narrowed it down to that area of code.  First time calling a php file would work (and 1000s of commits could happen successfully, but on the 2nd call NULL/unsuccessful commit occured). I believe the params were eventually getting set incorrectly causing the error to occur on callback after the 2nd call to a php file.  The `nr_php_instrument_datastore_operation_call` handles this more correctly for the `commit` operation.  After the 2nd call,  NULL no longer occurs, and the failure to commit no longer occurs.  Tested across 1000s of PHP calls calling 100s of commits.

**Review by joshuabenuck — APPROVED** [review]

**Review by Fahmy-Mohammed — APPROVED** [review]

**Comment by Webonaute** [comment]
This make me completely nuts in the last 2 days! glad you fixed this!

**Pull request merged**
