### PR TITLE
feat(agent): Bump to 9.22.0 (cosmos)

### PR DESCRIPTION
**Pull request by mfulb**
Bumping dev to next release version and codename.

### CODE REVIEW

**Review by misiekn — APPROVED** [review]

**Review by zsistla — APPROVED** [review]

**Comment by mfulb** [comment]
ok jenkins

**Comment by mfulb** [comment]
ok jenkins

**Comment by mfulb** [comment]
ok jenkins

**Comment by mfulb** [comment]
ok jenkins

**Pull request merged**
