### PR TITLE
Bump release version to 9.19.0 and choose new codename

### PR DESCRIPTION
**Pull request by mikefulb**

### CODE REVIEW

**Review by Fahmy-Mohammed — APPROVED** [review]

**Comment by Fahmy-Mohammed** [comment]
We should probably rebase this PR onto the dev branch otherwise, it looks great!

**Review by zsistla — APPROVED** [review]
Thanks!  Once it's rebased off of dev ([here's why](https://github.com/newrelic/newrelic-php-agent/blob/main/CONTRIBUTING.md#pull-requests)), it looks good to merge.

**Comment by zsistla** [comment]
ok jenkins

**Comment by zsistla** [comment]
ok jenkins

**Comment by mfulb** [comment]
Will recreate from mfulb account.

**Pull request closed without merging**
