### PR TITLE
feat(agent): add support for PHP 8.3

### PR DESCRIPTION
**Pull request by bduranleau-nr**

### CODE REVIEW

**Comment by rvanlaak** [comment]
After a great start in September, it now seems it has been a bit silent on this PR. Any update on what still would need to happen? The final release candidate will be available two days from now, and the general availability release will be in three weeks: https://wiki.php.net/todo/php83

**Comment by Ak-x** [comment]
Hello @rvanlaak, the Php 8.3 release depends on our work in [ObserverAPI](https://github.com/newrelic/newrelic-php-agent/tree/oapi). Once resolved 8.3 should be straightforward.

**Comment by rvanlaak** [comment]
Thanks for the update @Ak-x , that looks like a major change to the approach, exciting! Work on ObserverAPI started over a year ago and does not have a draft PR yet, while in the meanwhile the PHP 8.2 support on the agent was able to get released.

Can you share some more visibility on the prioritization and dependency of ObserverAPI you refer to, over agent language support? Teams are eager on that in order to being able to complete the tech roadmapping they're working on.

**Comment by parallels999** [comment]
PHP 8.3 already released

**Comment by abobija** [comment]
Bump

**Comment by bduranleau-nr** [comment]
PHP 8.3 support was released in [10.15.0.4](https://github.com/newrelic/newrelic-php-agent/releases/tag/v10.15.0.4).
OAPI will be rebased to include 8.3 support.

**Pull request closed without merging**
